# Generated by Django 5.0.3 on 2024-04-20 03:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_election_se_result_status'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messanger',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 20, 3, 45, 38, 707957, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 20, 3, 45, 38, 707957, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.commissioners'),
        ),
    ]
