# Generated by Django 5.0.3 on 2024-04-20 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_messanger_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='expird_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messanger',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 20, 3, 54, 36, 458547, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 4, 20, 3, 54, 36, 458547, tzinfo=datetime.timezone.utc)),
        ),
    ]
