# Generated by Django 5.0.3 on 2024-04-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='voter_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
