# Generated by Django 5.0.3 on 2024-04-18 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_email_verified_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='Election_Start',
            field=models.DateTimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_end',
            field=models.DateTimeField(default=datetime.time(17, 0)),
        ),
    ]
