# Generated by Django 5.0.3 on 2024-04-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_vote_is_varified_vote_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='Election_Start',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_end',
            field=models.TimeField(default='17:00'),
        ),
    ]
