# Generated by Django 5.0.3 on 2024-04-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_election_election_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='Election_Start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_end',
            field=models.DateField(),
        ),
    ]
