# Generated by Django 5.0.3 on 2024-04-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_election_election_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='able_to_vote',
            field=models.BooleanField(default=False),
        ),
    ]
