# Generated by Django 5.0.3 on 2024-04-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_election_able_to_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='canditats',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canditats',
            name='mul_niti',
            field=models.TextField(blank=True, null=True),
        ),
    ]
