# Generated by Django 5.0.3 on 2024-04-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='forget_pass_status',
            field=models.BooleanField(default=False),
        ),
    ]
